preprocess:
  data_name: pems04
  path: data/PEMS04/PEMS04.npz
  input_length: 12
  output_length: 12
  train_ratio: 0.6
  valid_ratio: 0.2
  test_ratio: 0.2
  mode: "test"
model:
  input_length: 12
  output_length: 12
  hidden: 256
  m: 800
  device: 7
train:
  batch_size: 32
  epoch: 100
  learning_rate: 0.001
  head: 4
  num_Period_Block: 8
 